-- Public certificate PDFs are displayed in the public portfolio's custom PDF viewer.
-- The certificates bucket remains private, while signed URLs are generated by the
-- server route. This SELECT policy lets Supabase Storage authorize those signed reads.
create policy "public certificate pdf read" on storage.objects
for select to anon, authenticated
using (bucket_id = 'certificates');
